apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: treaties.flow.gideas.io
spec:
  group: flow.gideas.io
  scope: Namespaced
  names:
    plural: treaties
    singular: treaty
    kind: Treaty
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                caCert:
                  type: string
                allowedSubjects:
                  type: array
                  items:
                    type: string
                allowedWorkitemTypes:
                  type: array
                  items:
                    type: string
                maxBundleSize:
                  type: string
              required:
                - name
                - caCert
