apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workitemtypes.flow.gideas.io
spec:
  group: flow.gideas.io
  scope: Namespaced
  names:
    plural: workitemtypes
    singular: workitemtype
    kind: WorkitemType
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                requiredArtefacts:
                  type: array
                  items:
                    type: string
                terminalContract:
                  type: string
              required:
                - name
