package main

import (
	"bytes"
	"fmt"
	"os"
	"text/template"

	"gopkg.in/yaml.v3"
)

type NodeConfig struct {
	Name           string
	Image          string
	ConfigMap      string `yaml:"configMap"`
	Ollama         bool
	Librarian      bool
	EventBus       bool `yaml:"eventBus"`
	FrictionLedger bool `yaml:"frictionLedger"`
}

type Config struct {
	Nodes []NodeConfig
}

func main() {
	dataPath := "../../nodes/haiku-manifests/deployments.yaml.data"
	outputPath := "../../nodes/haiku-manifests/deployments.yaml"
	templatePath := "template.yaml"

	// Read data file
	data, err := os.ReadFile(dataPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "reading data file: %v\n", err)
		os.Exit(1)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		fmt.Fprintf(os.Stderr, "parsing data file: %v\n", err)
		os.Exit(1)
	}

	// Read template
	tmplRaw, err := os.ReadFile(templatePath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "reading template: %v\n", err)
		os.Exit(1)
	}

	tmpl, err := template.New("deployment").Parse(string(tmplRaw))
	if err != nil {
		fmt.Fprintf(os.Stderr, "parsing template: %v\n", err)
		os.Exit(1)
	}

	// Generate output
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by tools/generate-deployments. Do not edit manually.\n")
	buf.WriteString("# Regenerate: cd tools/generate-deployments && go run .\n")

	for i, node := range cfg.Nodes {
		if i > 0 {
			buf.WriteString("---\n")
		}
		if err := tmpl.Execute(&buf, node); err != nil {
			fmt.Fprintf(os.Stderr, "executing template for %q: %v\n", node.Name, err)
			os.Exit(1)
		}
	}

	// Write output
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %d deployments to %s\n", len(cfg.Nodes), outputPath)
}
