apiVersion: flow.gideas.io/v1
kind: GovernedArtefact
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: governedartefact-sample
spec:
  # TODO(user): Add fields here
