apiVersion: flow.gideas.io/v1
kind: Treaty
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: treaty-sample
spec:
  remoteName: remote-flow
  direction: import
  caCert: |
    -----BEGIN CERTIFICATE-----
    ZXhhbXBsZQ==
    -----END CERTIFICATE-----
  allowedSubjects:
    - spiffe://remote-flow/embassy
  allowedImportTypes:
    - law-petition
  maxBundleSize: 10Mi
