# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/flow.gideas.io_foundryflows.yaml
- bases/flow.gideas.io_foundrynodes.yaml
- bases/flow.gideas.io_workitems.yaml
- bases/flow.gideas.io_governedartefacts.yaml
- bases/flow.gideas.io_laws.yaml
- bases/flow.gideas.io_treaties.yaml
- bases/flow.gideas.io_flowsupportservices.yaml
- bases/flow.gideas.io_codificationservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
