package schema

// reservedWords contains the set of Cypher and LadybugDB reserved words that
// cannot be used as type names or property names.
// ponytail: Verified against LadybugDB v0.17.0's parser behavior. The list includes
// standard Cypher keywords plus LadybugDB-specific keywords like INDEX and CONTAINS.
// If a future LadybugDB version adds reserved words, they must be added here to
// prevent schemas that pass validation but fail at table-creation time.
var reservedWords = map[string]bool{
	"ALL":        true,
	"AND":        true,
	"AS":         true,
	"ASC":        true,
	"ASCENDING":  true,
	"BY":         true,
	"CALL":       true,
	"CASE":       true,
	"CONTAINS":   true,
	"CREATE":     true,
	"DELETE":     true,
	"DESC":       true,
	"DESCENDING": true,
	"DETACH":     true,
	"DISTINCT":   true,
	"DROP":       true,
	"ELSE":       true,
	"END":        true,
	"ENDS":       true,
	"EXISTS":     true,
	"FALSE":      true,
	"FOREACH":    true,
	"IN":         true,
	"INDEX":      true,
	"IS":         true,
	"LIMIT":      true,
	"LOAD":       true,
	"MATCH":      true,
	"MERGE":      true,
	"NOT":        true,
	"NULL":       true,
	"ON":         true,
	"OPTIONAL":   true,
	"OR":         true,
	"ORDER":      true,
	"REMOVE":     true,
	"RETURN":     true,
	"SET":        true,
	"SKIP":       true,
	"START":      true,
	"STARTS":     true,
	"THEN":       true,
	"TRUE":       true,
	"UNION":      true,
	"UNWIND":     true,
	"USING":      true,
	"WHEN":       true,
	"WHERE":      true,
	"WITH":       true,
	"XOR":        true,
	"YIELD":      true,
}
