apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: foundry-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: operator
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          - --librarian-address=flow-librarian.default.svc.cluster.local:50058
          - --archivist-address=flow-archivist.default.svc.cluster.local:50054
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        env:
        - name: OLLAMA_API_KEY
          value: "9de147e88aaa408b98865170b2d20f45.BIRBE7eQGD_B5wnHn-ZyB6gr"
        ports: []
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
