apiVersion: flow.gideas.io/v1
kind: FoundryFlow
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: basic-linear-flow
  namespace: default
spec:
  entryContracts:
    standard-entry:
      document: []
  exitContracts:
    standard-exit:
      document: []
  governancePolicy:
    maxVisits: 10
    defaultTimeout: "1h"
    maxTimeout: "4h"
